sudo: required
dist: trusty
cache: pip
language: python
python:
- 2.7
install:
- pip install -U pip setuptools pip-tools
- pip install -r dev_requirements.txt
script:
- echo "Hello world, I'll do something real useful.. Real soon!"
deploy:
  provider: pypi
  user: atmosphere
  distributions: sdist bdist_wheel
  password:
    secure: UYCYQ6gGCTp88vC5xmqVoQbYTiUQ0AxNF9FNF3ttQj10tQqEUuv9cOVr1OKNioQewkxQtLV0h6UGvjIulXIywaVTNoBknuIZc25pQkezgZYepm1y8QfTKTvbBDM1rKGGGJzaDfI2Kk4R8xdONW+KbacJSNv8G/SLPqryFLz1Z0qcJtc48/MjtEzFWShzg5k0YSBn140k+wa9NCcfbpb7mLF6Eja7v5mPSOra0OUAz6rusW9yTXF+ZE8BGAOmOaVbki3AOa1zs2gKiV07JpwqgAwthNIPNFIKsQWqpx2xUPj1IaY3EnECB05eKKWuYYDBGZTJWCG7jvXmrZG2ddIk5K1+bDmkY5IIURZbyEV/2EpysNhDa9gy2nfm1G8jNiBK3dGR28cf5Yiw8qCZkkJzkXqf9P3Gbxpm05DyF5G30J0Vypopf1Lev8jVkuRuDpE/wctjZTZuNZ+5f6v1FHwq6ikJ/LijRu4WD2jcSRCLyBkxiLVNRH5apJdglFxl9UQQ5Hw+KNB1rsmR3dXd1LDjyz6cT4HdHwRMqOPINaHomsUQu7pu2qEI7dGH9e0+K05iq0FsxGogVsoCr30vXOMXWymzmsU9EVS3T2XlO9PO+Phz3ASbloe07/9rs6OgzsPf5xjjbwiCURsRJsnmMq7Y0Zp4jzaelymXTnJSjzJWnag=
  on:
    tags: true
